const sortData = {
  sortByRel: {
    product: '17067',
    page: 0,
    count: 5,
    results: [
      {
        review_id: 347987,
        rating: 3,
        summary: 'Gate keepers of hell.',
        recommend: true,
        response: null,
        body: "I hate cucumber pls dont throw it at me i see a bird i stare at it i meow at it i do a wiggle come here birdy look at dog hiiiiiisssss. Pet my belly, you know you want to; seize the hand and shred it! spend all night ensuring people don't sleep sleep all day, claws in the eye of the beholder so attack feet, ignore the human until she needs to get up, ",
        date: '2021-04-20T00:00:00.000Z',
        reviewer_name: 'JoeCool',
        helpfulness: 1,
        photos: [],
      },
      {
        review_id: 348346,
        rating: 4,
        summary: 'Awesome review again',
        recommend: true,
        response: null,
        body: 'Some random text Some random text Some random text Some random text',
        date: '2021-04-28T00:00:00.000Z',
        reviewer_name: 'Marco Polo',
        helpfulness: 0,
        photos: [],
      },
      {
        review_id: 406612,
        rating: 5,
        summary: 'Lorem ipsum',
        recommend: false,
        response: null,
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        date: '2021-06-05T00:00:00.000Z',
        reviewer_name: 'Zoro',
        helpfulness: 0,
        photos: [],
      },
      {
        review_id: 406600,
        rating: 5,
        summary: 'What are you waiting for',
        recommend: false,
        response: null,
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        date: '2021-06-05T00:00:00.000Z',
        reviewer_name: 'Luffy',
        helpfulness: 0,
        photos: [],
      },
      {
        review_id: 406598,
        rating: 5,
        summary: 'This works',
        recommend: false,
        response: null,
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        date: '2021-06-05T00:00:00.000Z',
        reviewer_name: 'Lorem',
        helpfulness: 0,
        photos: [],
      },
    ],
  },

  sortByHelpful: {
    product: '17068',
    page: 0,
    count: 5,
    results: [
      {
        review_id: 288940,
        rating: 5,
        summary: 'Best Review Ever!',
        recommend: true,
        response: null,
        body: 'This Review is great, so is the person who made this module!',
        date: '2021-03-12T00:00:00.000Z',
        reviewer_name: 'Tear-in',
        helpfulness: 33,
        photos: [],
      },
      {
        review_id: 348184,
        rating: 4,
        summary: 'These make me the coolest cat',
        recommend: false,
        response: null,
        body: "Hit you unexpectedly love blinks and purr purr purr purr yawn so try to jump onto window and fall while scratching at wall found somthing move i bite it tail and eat all the power cords murr i hate humans they are so annoying or kitty pounce, trip, faceplant you didn't see that no you didn't definitely didn't lick, lick, lick, and preen away the embarrassment. In the middle of the night i crawl onto your chest and purr gently to help you sleep while happily ignoring when being called do i like standing on litter cuz i sits when i have spaces, my cat buddies have no litter i live in luxury cat life pet me pet me pet me pet me, bite, scratch, why are you petting me for purr as loud as possible, be the most annoying cat that you can, and, knock everything off the table but i hate cucumber pls dont throw it at me, cough. Just going to dip my paw in your coffee and do a taste test - oh never mind i forgot i don't like coffee",
        date: '2021-04-27T00:00:00.000Z',
        reviewer_name: 'catShady',
        helpfulness: 2,
        photos: [],
      },
      {
        review_id: 348183,
        rating: 4,
        summary: 'Why did I not know about this until now',
        recommend: false,
        response: null,
        body: "Hit you unexpectedly love blinks and purr purr purr purr yawn so try to jump onto window and fall while scratching at wall found somthing move i bite it tail and eat all the power cords murr i hate humans they are so annoying or kitty pounce, trip, faceplant you didn't see that no you didn't definitely didn't lick, lick, lick, and preen away the embarrassment. In the middle of the night i crawl onto your chest and purr gently to help you sleep while happily ignoring when being called do i like standing on litter cuz i sits when i have spaces, my cat buddies have no litter i live in luxury cat life pet me pet me pet me pet me, bite, scratch, why are you petting me for purr as loud as possible, be the most annoying cat that you can, and, knock everything off the table but i hate cucumber pls dont throw it at me, cough. Just going to dip my paw in your coffee and do a taste test - oh never mind i forgot i don't like coffee",
        date: '2021-04-27T00:00:00.000Z',
        reviewer_name: 'catShady',
        helpfulness: 1,
        photos: [
          {
            id: 614290,
            url: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8Y2F0JTIwaW4lMjBzdW5nbGFzc2VzfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
          },
        ],
      },
      {
        review_id: 348182,
        rating: 4,
        summary: 'I am the coolest customer',
        recommend: false,
        response: null,
        body: "Hit you unexpectedly love blinks and purr purr purr purr yawn so try to jump onto window and fall while scratching at wall found somthing move i bite it tail and eat all the power cords murr i hate humans they are so annoying or kitty pounce, trip, faceplant you didn't see that no you didn't definitely didn't lick, lick, lick, and preen away the embarrassment. In the middle of the night i crawl onto your chest and purr gently to help you sleep while happily ignoring when being called do i like standing on litter cuz i sits when i have spaces, my cat buddies have no litter i live in luxury cat life pet me pet me pet me pet me, bite, scratch, why are you petting me for purr as loud as possible, be the most annoying cat that you can, and, knock everything off the table but i hate cucumber pls dont throw it at me, cough. Just going to dip my paw in your coffee and do a taste test - oh never mind i forgot i don't like coffee",
        date: '2021-04-27T00:00:00.000Z',
        reviewer_name: 'catShady',
        helpfulness: 1,
        photos: [
          {
            id: 614289,
            url: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8Y2F0JTIwaW4lMjBzdW5nbGFzc2VzfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
          },
        ],
      },
      {
        review_id: 348185,
        rating: 4,
        summary: 'These are awesome',
        recommend: false,
        response: null,
        body: "Hit you unexpectedly love blinks and purr purr purr purr yawn so try to jump onto window and fall while scratching at wall found somthing move i bite it tail and eat all the power cords murr i hate humans they are so annoying or kitty pounce, trip, faceplant you didn't see that no you didn't definitely didn't lick, lick, lick, and preen away the embarrassment. In the middle of the night i crawl onto your chest and purr gently to help you sleep while happily ignoring when being called do i like standing on litter cuz i sits when i have spaces, my cat buddies have no litter i live in luxury cat life pet me pet me pet me pet me, bite, scratch, why are you petting me for purr as loud as possible, be the most annoying cat that you can, and, knock everything off the table but i hate cucumber pls dont throw it at me, cough. Just going to dip my paw in your coffee and do a taste test - oh never mind i forgot i don't like coffee",
        date: '2021-04-27T00:00:00.000Z',
        reviewer_name: 'catShady',
        helpfulness: 0,
        photos: [],
      },
    ],
  },

  sortByNewest: {
    product: '17069',
    page: 0,
    count: 5,
    results: [
      {
        review_id: 289097,
        rating: 5,
        summary: 'Testing out Cloudinary',
        recommend: true,
        response: null,
        body: 'Is there a picture of a cat? There should be a picture of a cat...',
        date: '2021-03-13T00:00:00.000Z',
        reviewer_name: 'DocMcFries',
        helpfulness: 60,
        photos: [
          {
            id: 496791,
            url: 'https://res.cloudinary.com/mcvey/image/upload/v1615677930/xkzemfcpcnizschf9mai.jpg',
          },
        ],
      },
      {
        review_id: 347935,
        rating: 4,
        summary: 'Super Good',
        recommend: false,
        response: null,
        body: "Cats making all the muffins cat mojo sit by the fire, thug cat morning beauty routine of licking self. Sit in a box for hours if it fits i sits and cat dog hate mouse eat string barf pillow no baths hate everything shove bum in owner's face like camera lens or attack the dog then pretend like nothing happened.",
        date: '2021-04-16T00:00:00.000Z',
        reviewer_name: 'jessCodeNinja',
        helpfulness: 30,
        photos: [
          {
            id: 614110,
            url: 'https://images.unsplash.com/photo-1589578228447-e1a4e481c6c8?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTB8fGtleWJvYXJkfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
          },
          {
            id: 614112,
            url: 'https://images.unsplash.com/photo-1595045051853-05ef47bdfdbe?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTZ8fGtleWJvYXJkfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
          },
          {
            id: 614111,
            url: 'https://images.unsplash.com/photo-1598662779094-110c2bad80b5?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fGtleWJvYXJkfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
          },
        ],
      },
      {
        review_id: 348266,
        rating: 5,
        summary: 'Love it!',
        recommend: true,
        response: null,
        body: 'super good great wonderful totally nice and superb ',
        date: '2021-04-27T00:00:00.000Z',
        reviewer_name: 'Joe',
        helpfulness: 20,
        photos: [],
      },
      {
        review_id: 348092,
        rating: 1,
        summary: 'DO NOT BUY THESE MORNING JOGGERS',
        recommend: false,
        response: null,
        body: "\"It was only after it arrived that I looked closely at the title and realized it said 'How to Avoid Huge SHIPS'. A simple error that means I am still treading on massive examples of canine excrement.\"\n",
        date: '2021-04-25T00:00:00.000Z',
        reviewer_name: 'Dom Stepek',
        helpfulness: 10,
        photos: [
          {
            id: 614260,
            url: 'http://res.cloudinary.com/dl6evetkp/image/upload/v1619380636/project%20catwalk/qb4yotcznkw0prc483ma.jpg',
          },
          {
            id: 614261,
            url: 'http://res.cloudinary.com/dl6evetkp/image/upload/v1619380639/project%20catwalk/aisvhzs9bykfkmfhqysr.png',
          },
        ],
      },
      {
        review_id: 347961,
        rating: 3,
        summary: "I'm enjoying wearing these shades",
        recommend: false,
        response: null,
        body: 'Comfortable and practical.',
        date: '2021-04-18T00:00:00.000Z',
        reviewer_name: 'slimShady',
        helpfulness: 0,
        photos: [
          {
            id: 614154,
            url: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8Y2F0JTIwaW4lMjBzdW5nbGFzc2VzfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
          },
        ],
      },
    ],
  },
};

module.exports = {
  sortData,
};
